---
# File locations on AWS instance
inputs:
  namere: 'DS-15\d+'
  regions: /encrypted/permanent/color_panel_21.bed
  vcfs:
    - /encrypted/permanent/vcf/*DS-15*vcf.gz
    - /encrypted/permanent/vcf/first_color_vcfs/*.vcf.gz
  bams:
    - /encrypted/permanent/bams/*DS-15*.bam
  cnvs: /encrypted/permanent/FF1-July-2014+labcorp-sept2014-1.cnvs-to-import.bed
resources:
  gatk: /encrypted/permanent/resources/GenomeAnalysisTK.jar
  ref_file: /encrypted/permanent/resources/GRCh37/seq/GRCh37.fa
annotations:
  rmsk: /encrypted/permanent/regions/GRCh37.rmsk.bed.gz
  lcr: /encrypted/permanent/regions/LCR.bed.gz
  #segdup: /encrypted/permanent/regions/GRCh37.segdup.bed.gz
  #grc_patch: /encrypted/permanent/regions/GRC_patch_regions.bed.gz
# Filters to apply. Comment out to get full discordants with no filtering
filters:
  - [min0, ColorRemoveDepth]
  - [min1, ColorRemoveRegion]
  - [max, ColorReview]
remap:
  # Swapped files and group names
  BH9TK7ADXX_DS-159807_AAGGTAC: DS-159815
  BH9TK7ADXX_DS-159807_ACGTATC: DS-159815
  BH9TK7ADXX_DS-159822_ACTATGC: DS-156119
  BH9TK7ADXX_DS-159822_ACACAGA: DS-156119
  BH9TK7ADXX_DS-159813_ACAGCAG: DS-159807
  BH9TK7ADXX_DS-159813_AGAGTCA: DS-159807
  BH9TK7ADXX_DS-159815_ACCTCCA: DS-159822
  BH9TK7ADXX_DS-156119_ACGCTCG: DS-159813
